language: objective-c
osx_image: xcode11.2

env:
  global:
    - WORKSPACE: BraintreeDropIn.xcworkspace
    - SCHEME: DropInDemo
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.3,name=iPhone 7"
    - DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone 8 Plus"
    - DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone Xs"
    - DESTINATION="platform=iOS Simulator,OS=13.2,name=iPhone 11"

install:
  - bundle install
  - bundle exec pod repo update --silent
  - travis_wait bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" test | xcpretty
