language: objective-c
osx_image: xcode11.2
xcode_workspace: BraintreeDropIn.xcworkspace
xcode_scheme: DropInDemo
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8

install:
  - bundle install
  - bundle exec pod repo update --silent
  - travis_wait bundle exec pod install

